### PR TITLE
Support the mainstream Clang compiler

### PR DESCRIPTION
**Pull request by AlisdairM**
This patch updates the library features component, as
experimentally determined, to build and pass test drivers
with hte recent Clang 3.9.1 compiler on macOS.  It makes
no attempt to determine which earlier versions do not
offer this level of support, nor test the recently released
Clang 4.0 compiler/library for additional support.

### CODE REVIEW

**Comment by abeels** [comment]
This patch would make BDE assume that all clang compilers running in C++11 mode have of the library features supplied with the libc++ that ships with clang 3.9.1.  We'll need a lot more granularity than that.

Our bias has been to not declare a library feature unless we know that we actually provide it, so we would prefer to (mistakenly) say that 3.9.1 does not provide feature X than (mistakenly) say that 3.7.0 does provide feature X.

I think you'll need to update this patch after answering the following questions:

1. Can we distinguish between libc++ and libstdc++?
2. For each library flavor (or just libc++ if we can't distinguish between the two), which features start being supported at which clang versions.

Somewhere in here there is probably a good case for refactoring `bsls_libraryfeatures` so that it allows clients to declare the library vendor and library version they are using via `-D` on the command line, for non-standard installations.

**Comment by kpfleming** [comment]
Relying on version numbers and library names is incredibly fragile, especially making assumptions about things that are likely to be installed together. It would be far better to use feature-test macros (if possible) to determine if the features required are available, regardless of how they are provided.

Of course, that may be purely academic and impossible to implement in reality.

**Comment by apaprocki** [comment]
And if feature tests can't be performed...

`libc++` can be detected in the preprocessor by checking for `_LIBCPP_VERSION`. If we require at least Clang 3.3 to build, you can assume that in C++11 mode using `libc++`, all C++11 library features exist.

**Comment by mversche** [comment]
Certainly feature test macros would be good (thought, off hand, I thought those mostly applied to compiler features, not library features).

One of the feature test macros we wanted to provide was one that indicated the flavor of standard library we were building against (which would be based on something like LIBCPP_VERSION), but that was cut from the first release of `bsls_libraryfeatures`.  Maybe it needs to be added as part of this fix...

**Comment by hyrosen** [comment]
On our nylnxbldo4 machine, clang++ run with -stdlib=libc++ can't find any of the C++ headers.  I think for our own purposes we should assume that clang++ on Linux doesn't use libc++ and that on Darwin it does.  I would very much prefer that we don't try to come up with a finer identification system than we need for our own actual, not theoretical, configurations.

**Comment by apaprocki** [comment]
See this: https://gist.github.com/apaprocki/2dc1041c8e88a293890750dca4181c91

There are already a ton of built-in `_LIBCPP_*` prefixed feature defines that exist. You can most likely reuse what the compiler already tells you.

Specifically you can see things like `_LIBCPP_STD_VER` and things like `_LIBCPP_TUPLE`.

**Comment by apaprocki** [comment]
@hyrosen `libc++` is detected by its own set of pre-processor defines and has nothing to do with `clang++` being used.

**Comment by hyrosen** [comment]
Do we do supported builds with libc++ at Bloomberg other than on Darwin?

**Comment by apaprocki** [comment]
@hyrosen No, we have never had a need to. But we could easily do so on Linux if we need to be able to test it.

**Comment by AlisdairM** [comment]
I think Alex has nailed the issue, and resolving it is more work than would occur in this simple pull request.  The problem is that we are conflating compiler and library - where in practice we support many more compilers and versions than libraries.

The appropriate fix appears to be to split the library features header into two phases - first, it attempts to detect the library in use, with similar autodetection machinery we are using for the compiler-version.  Then, having defined a consistent set of BDE macros to identify which library is in use, we can define the BDE feature macros in a second per-library section.

Note that just because a library is implemented does not mean BDE will export it out of 'bsl'.  We have certain expectations of the language support and (lack of) library bugs before we define the feature macro - and for now we are trying to keep the set of library feature macros low, and fairly granular, as ideally we will move to a world where all compilers have a full C++11 library.  As our library detection shows though, that certainly does not happen before gcc 5.x and Clang 4.x - and may be even later.

**Comment by abeels** [comment]
Closing, pending either a more focused pull request, or a re-design of library feature detection.

**Pull request closed without merging**
