### PR TITLE
remove BSLS_PLATFORM_NO_64_BIT_LITERALS

### PR DESCRIPTION
**Pull request by gstrauss**
remove BSLS_PLATFORM_NO_64_BIT_LITERALS

### CODE REVIEW

**Comment by sbreitstein** [comment]
Internal ticket #61790493 created to track this.

**Comment by hyrosen** [comment]
Checked in. Review in <https://review.openbloomberg.com/D243>.

**Comment by gstrauss** [comment]
Alisdair still perceives value in the tests removed in the prior proposed patch.  Forced pushed a new patch which extends the tests in bsls_types.t.cpp to compilers which support numeric literals with suffix specifiers for values outside the range of int

**Comment by hyrosen** [comment]
Where do I look at this forced push code?

**Comment by gstrauss** [comment]
@hyrosen: https://github.com/bloomberg/bde/pull/171/files shows the updated patch.  You can click this link or click the "Files Changed" tab near the top of this github page (https://github.com/bloomberg/bde/pull/171), next to the "Conversation" tab (which is this page)

**Pull request merged**
