### PR TITLE
Linux on PowerPC port

### PR DESCRIPTION
**Pull request by gstrauss**
Linux on PowerPC initial platform, atomics support for gcc compiler

Also provides (same) atomics implementation for gcc on AIX on PowerPC, replacing the stub implementation bsls_atomicoperations_powerpc_aix_gcc

### CODE REVIEW

**Comment by mversche** [comment]
I've provided some additional comments on phabricator.   

Please provide a complete updated phabricator with the combined change-set you would like us to review/merge.  Sorry, I just can't work with the github code review system for change-sets covering multiple complex commits that overlap each other.

I'd note that 
5cb18fb seems to updates the copyright notice on one of the files, but I imagine the others also need to be updated

**Comment by gstrauss** [comment]
Still working on untangling alignment assumptions.  Will also include update to copyright to remove "(C)" for consistency.

**Comment by gstrauss** [comment]
Force-pushed update including changes for copyright consistency.

Latest commit includes porting of for bsls_alignment* components: "long double aligned at 8-byte ok on Linux on POWER".  Please note the commit message about incorrect assumption made by bsls_alignmenttotype.h that a type is aligned at least to its size.

**Comment by gstrauss** [comment]
rebased changes against current master and updated bsls_byteorderutil*.t.cpp for proper size of wchar_t on Linux on POWER

**Pull request merged**
